### ISSUE TITLE
文章内容页 图片与目录树重叠

### ISSUE THREAD

**Issue by Meilinhost** [huhexian/2012-huhexian#1]
文章内容页 如果图片放在顶部，会和目录树重叠，加个空格是否会更好
![22222222222222](https://github.com/huhexian/2012-huhexian/assets/3524108/2098dac9-552e-4626-8b8e-d6e666778954)

**Comment by huhexian** [comment]
这个确实在我能力范围之外了，你有没有好的办法，将目录框悬浮到左侧或者右侧空白处呢？

**Comment by Meilinhost** [comment]
@huhexian
我也搞不定尴尬😓
我在想找那句目录数代码 想办法给它下面加句空格，不知道行不行

**Comment by krystal-cao** [comment]
@Meilinhost @huhexian 
试试修改style.css文件的toc_container属性 改成 margin: 10px 0 10px 16px; 
应该有两处，分别是1400行和2908行
这样应该会给目录底部增加10px的空白，修改以后会变成这个样子
![WX20230906-093823@2x](https://github.com/huhexian/2012-huhexian/assets/13929955/94750d71-3073-4ede-9577-dcdfdf985237)

**Comment by huhexian** [comment]
> @Meilinhost @huhexian 试试修改style.css文件的toc_container属性 改成 margin: 10px 0 10px 16px; 应该有两处，分别是1400行和2908行 这样应该会给目录底部增加10px的空白，修改以后会变成这个样子 ![WX20230906-093823@2x](https://user-images.githubusercontent.com/13929955/265865645-94750d71-3073-4ede-9577-dcdfdf985237.png)

太感谢了！另外看到你fork了之后有代码修改，可以一起提交pr的。

**Comment by huhexian** [comment]
主题更新了，目录样式修改成悬浮在右侧，可以试试。
